pipeline {
    agent { label 'nodejs-24' }

    environment {
        IMAGE_NAME    = "repo.huangyp.cn/password-xl/password-xl-home-web"
        YARN_REGISTRY = "https://nexus.huangyp.cn/repository/npm-group/"

    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5'))
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {
        stage('Build & Push Image (BuildKit)') {
          steps {
            container('buildkit') {
              sh '''
              set -e

              echo "构建并推送镜像..."
              buildctl-daemonless.sh build \
                --frontend dockerfile.v0 \
                --local context="${WORKSPACE}/password-xl-home" \
                --local dockerfile="${WORKSPACE}/password-xl-home" \
                --opt filename=Dockerfile \
                --output type=image,\\"name=${IMAGE_NAME}:${BUILD_NUMBER},${IMAGE_NAME}:latest\\",push=true
              '''
            }
          }
        }

        // 部署到 Kubernetes 集群
        stage('Deploy to Kubernetes') {
            steps {
                container('kubectl') {
                    sh '''
                    set -euo pipefail

                    echo "🔁 使用当前构建镜像更新 Deployment，触发滚动发布..."
                    kubectl set image deployment/password-xl-home \
                      password-xl-home=${IMAGE_NAME}:${BUILD_NUMBER} \
                      -n password-xl

                    echo "⏳ 等待 Deployment 完成滚动更新..."
                    kubectl rollout status deployment/password-xl-home -n password-xl --timeout=120s
                    '''
                }
            }
        }
    }
}
