pipeline {
    agent { label 'nodejs-24' }

    environment {
        IMAGE_NAME    = "repo.huangyp.cn/password-xl/password-xl-web"
        YARN_REGISTRY = "https://nexus.huangyp.cn/repository/npm-group/"
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5'))
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {
        stage('Install & Build') {
            steps {
                container('node') {
                    sh '''
                    set -euo pipefail
                    yarn config set registry ${YARN_REGISTRY}

                    cd password-xl-web

                    echo "安装依赖..."
                    yarn install

                    echo "开始构建..."
                    yarn build
                    '''
                }
            }
        }

        stage('Build & Push Image (BuildKit)') {
            steps {
                container('buildkit') {
                    sh '''
                    set -e

                    echo "构建并推送镜像..."
                    buildctl-daemonless.sh build \
                      --frontend dockerfile.v0 \
                      --local context="${WORKSPACE}/password-xl-web" \
                      --local dockerfile="${WORKSPACE}/password-xl-web" \
                      --opt filename=Dockerfile \
                      --output type=image,\\"name=${IMAGE_NAME}:${BUILD_NUMBER},${IMAGE_NAME}:latest\\",push=true
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                container('kubectl') {
                    sh '''#!/bin/bash
                    set -euo pipefail

                    echo "🔁 使用当前构建镜像更新 Deployment，触发滚动发布..."
                    kubectl set image deployment/password-xl-web \
                      password-xl-web=${IMAGE_NAME}:${BUILD_NUMBER} \
                      -n "password-xl"

                    echo "⏳ 等待 Deployment 完成滚动更新..."
                    kubectl rollout status deployment/password-xl-web -n "password-xl" --timeout=270s

                    echo "✅ 部署完成: password-xl-web"
                    '''
                }
            }
        }
    }
}
