apiVersion: v1
kind: Service
metadata:
  name: password-xl-web
  namespace: password-xl
spec:
  type: ClusterIP
  selector:
    app: password-xl-web
  ports:
    - name: http
      targetPort: 80
      port: 80
