spring:
  application:
    name: password-xl-service

doc:
  openSource: https://github.com/peng0105/password-xl
  deploy: https://github.com/peng0105/password-xl/wiki/%E5%90%8E%E7%AB%AF%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3%E2%80%90docker