apiVersion: v1
kind: ServiceAccount
metadata:
  name: password-xl-web-deployer
  namespace: jenkins-agent
automountServiceAccountToken: false
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-jenkins-web-deployer
  namespace: password-xl
spec:
  podSelector:
    matchLabels:
      app: password-xl-web
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: jenkins-agent
          podSelector:
            matchLabels:
              password-xl.cn/web-deployer: 'true'
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: password-xl-web-deployer
  namespace: password-xl
rules:
  - apiGroups: [apps]
    resources: [deployments]
    resourceNames: [password-xl-web]
    verbs: [get, patch]
  - apiGroups: ['']
    resources: [pods]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: password-xl-web-deployer
  namespace: password-xl
subjects:
  - kind: ServiceAccount
    name: password-xl-web-deployer
    namespace: jenkins-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: password-xl-web-deployer
