apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildkit: unconfined
spec:
  serviceAccountName: jenkins-build
  automountServiceAccountToken: false
  nodeSelector:
    kubernetes.io/arch: amd64
  securityContext:
    fsGroup: 1000
  containers:
    - name: jnlp
      image: ${CI_AGENT_IMAGE}
    - name: tools
      image: ${CI_TOOLS_IMAGE}
      command: [sleep]
      args: [infinity]
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      env:
        - name: BUILDKIT_HOST
          value: tcp://127.0.0.1:1234
        - name: PYTHONUNBUFFERED
          value: '1'
      resources:
        requests: {cpu: '2', memory: 4Gi}
        limits: {cpu: '4', memory: 16Gi}
    - name: buildkit
      image: ${CI_BUILDKIT_IMAGE}
      args: [--addr, tcp://127.0.0.1:1234, --oci-worker-no-process-sandbox, --oci-worker-snapshotter, native]
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: {type: Unconfined}
      readinessProbe:
        exec:
          command: [buildctl, --addr, tcp://127.0.0.1:1234, debug, workers]
        initialDelaySeconds: 3
        periodSeconds: 3
      resources:
        requests: {cpu: '250m', memory: 256Mi}
        limits: {cpu: '2', memory: 2Gi}
