name: build service to Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: actions/setup-java@v3
        with:
          distribution: 'graalvm'
          java-version: '21'
          cache: gradle

      - name: Install native-image component
        run: gu install native-image


      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x ./password-xl-service/gradlew

      - name: Build native image using GraalVM
        working-directory: ./password-xl-service
        run: ./gradlew nativeCompile

      - name: Extract version from build.gradle
        id: extract_version
        working-directory: ./password-xl-service
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:${{ env.VERSION }} -t ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:latest ./password-xl-service

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:latest
