name: build web to Docker Image
 
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      volumes:
        - ubuntu_dockercache:/opt/dockercache
    env:
      DOCKER_REGISTRY: docker.io
      REPO_NAME: password-xl-web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v5
        with:
          node-version: 20.16.x

      - name: Install yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install dependencies
        run: yarn install
        working-directory: ./password-xl-web
 
      - name: Build Vue
        run: yarn run build
        working-directory: ./password-xl-web

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${{ github.ref }} | awk -F"/" '{print $3}' | awk -F"v" '{print $2}') >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}
