name: Build Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      volumes:
        - ubuntu_dockercache:/opt/dockercache
    outputs:
      UPLOAD_URL: ${{ steps.set_output.outputs.UPLOAD_URL }}
      REPO_VERSION: ${{ steps.set_output.outputs.REPO_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v5
        with:
          node-version: 20.16.x

      - name: Install yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install dependencies
        run: yarn install
        working-directory: ./password-xl-web

      - name: Set up Jdk21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x ./password-xl-service/gradlew

      - name: Get Meta
        working-directory: ./password-xl-web
        run: |
          echo REPO_VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
          echo REPO_SERVER_VERSION=$(./gradlew -q printVersion) >> $GITHUB_ENV

      - name: Build vue
        run: yarn run build
        working-directory: ./password-xl-web

      - name: Build jar
        working-directory: ./password-xl-service
        run: ./gradlew bootJar

      - name: zip package
        run: |
          zip -r password-xl-web/dist.zip password-xl-web/dist
          tar -zcvf password-xl-web/dist.tar.gz password-xl-web/dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.REPO_VERSION }}
          release_name: Release ${{ env.REPO_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset webZip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: password-xl-web/dist.zip
          asset_name: password-xl-web-dist-${{ env.REPO_VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset webGzip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: password-xl-web/dist.tar.gz
          asset_name: password-xl-web-dist-${{ env.REPO_VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset serviceJar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: password-xl-service/build/libs/password-xl-service-${{ env.REPO_SERVER_VERSION }}.jar
          asset_name: password-xl-service-${{ env.REPO_VERSION }}.jar
          asset_content_type: application/octet-stream

      - name: Set output for upload_url
        id: set_output
        run: |
          echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> "$GITHUB_OUTPUT"
          echo "REPO_VERSION=${{ env.REPO_VERSION }}" >> "$GITHUB_OUTPUT"

  build-windows:
    runs-on: windows-latest
    needs: build-project
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.x

      - name: Install dependencies
        run: yarn install
        working-directory: ./password-xl-web

      - name: Get Meta 1
        working-directory: ./password-xl-web
        run: echo REPO_VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV

      - name: Build exe
        working-directory: ./password-xl-web
        run: yarn run dist-to-windows

      - name: Upload Release Asset 3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.build-project.outputs.UPLOAD_URL}}
          asset_path: password-xl-web/build/password-XL-Windows-${{needs.build-project.outputs.REPO_VERSION}}.exe
          asset_name: password-xl-win-${{needs.build-project.outputs.REPO_VERSION}}.exe
          asset_content_type: application/octet-stream

  build-macos:
    runs-on: macos-latest
    needs: build-project

    steps:
      - env:
          UPLOAD_URL: ${{needs.build-project.outputs.UPLOAD_URL}}
          REPO_VERSION: ${{needs.build-project.outputs.REPO_VERSION}}
        run: echo "$UPLOAD_URL $REPO_VERSION"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.x

      - name: Install dependencies
        run: yarn install
        working-directory: ./password-xl-web

      - name: Get Meta 1
        working-directory: ./password-xl-web
        run: echo REPO_VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV

      - name: Build macOS app
        working-directory: ./password-xl-web
        run: yarn run dist-to-mac

      - name: Upload Release Asset macOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.build-project.outputs.UPLOAD_URL}}
          asset_path: password-xl-web/build/password-XL-Mac-${{needs.build-project.outputs.REPO_VERSION}}.dmg
          asset_name: password-xl-mac-${{needs.build-project.outputs.REPO_VERSION}}.dmg
          asset_content_type: application/octet-stream

  build-linux:
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - env:
          UPLOAD_URL: ${{needs.build-project.outputs.UPLOAD_URL}}
          REPO_VERSION: ${{needs.build-project.outputs.REPO_VERSION}}
        run: echo "$UPLOAD_URL $REPO_VERSION"

      - name: 检出代码
        uses: actions/checkout@v4

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v5
        with:
          node-version: 20.16.x

      - name: Install dependencies
        run: yarn install
        working-directory: ./password-xl-web

      - name: Get Meta 1
        working-directory: ./password-xl-web
        run: echo REPO_VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV

      - name: Build Linux app
        working-directory: ./password-xl-web
        run: yarn run dist-to-linux

      - name: Upload Release Asset Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.build-project.outputs.UPLOAD_URL}}
          asset_path: password-xl-web/build/password-XL-Linux-${{needs.build-project.outputs.REPO_VERSION}}.tar.gz
          asset_name: password-xl-linux-${{needs.build-project.outputs.REPO_VERSION}}.tar.gz
          asset_content_type: application/gzip
