name: 发布后端服务Docker镜像

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      REPO_NAME: password-xl-service
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Jdk21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 版本输出
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: 获取gradle缓存
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: 设置gradlew可执行权限
        run: chmod +x ./password-xl-service/gradlew

      - name: 编译原生镜像
        working-directory: ./password-xl-service
        run: ./gradlew nativeCompile

      - name: 获取版本信息
        id: extract_version
        working-directory: ./password-xl-service
        run: |
          echo REPO_VERSION=$(./gradlew -q printVersion) >> $GITHUB_ENV

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 发布镜像
        uses: docker/build-push-action@v6
        with:
          context: .
          file: password-xl-service/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{env.REPO_VERSION}}
