name: 发布前端服务Docker镜像

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      volumes:
        - ubuntu_dockercache:/opt/dockercache
    env:
      DOCKER_REGISTRY: docker.io
      REPO_NAME: password-xl-web
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 nvm
        uses: dcodeIO/setup-node-nvm@v5
        with:
          node-version: 20.16.x

      - name: 缓存 yarn 模块
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/cache
            ~/.yarn/unplugged
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 安装 yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: 安装依赖
        run: yarn install
        working-directory: ./password-xl-web

      - name: 编译前端项目
        run: yarn run build
        working-directory: ./password-xl-web

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 安装 Buildx
        uses: docker/setup-buildx-action@v3

      - name: 获取本次发布的版本信息
        id: meta
        run: |
          echo REPO_VERSION=$(node -p "require('./password-xl-web/package.json').version") >> $GITHUB_ENV

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 发布镜像
        uses: docker/build-push-action@v6
        with:
          context: .
          file: password-xl-web/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{env.REPO_VERSION}}
        
