name: Data Transfer Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  set-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set output using set-output
        id: set_output_example
        run: echo "::set-output name=output_variable::HelloOutput"

      - name: Set environment variable using GITHUB_ENV
        run: echo "env_variable=HelloEnv" >> $GITHUB_ENV

      - name: Set environment variable for subsequent steps
        run: |
          echo "env_variable_step=HelloStepEnv" >> $GITHUB_ENV
          echo "::set-output name=output_step_variable::HelloStepOutput"

      - name: Print outputs to verify
        run: |
          echo "Output Variable: ${{ steps.set_output_example.outputs.output_variable }}"
          echo "Environment Variable: ${{ env.env_variable }}"
          echo "Environment Variable Step: ${{ env.env_variable_step }}"
          echo "Output Step Variable: ${{ steps.set_output_example.outputs.output_step_variable }}"

  use-data:
    runs-on: ubuntu-latest
    needs: set-data

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print received outputs
        run: |
          echo "Output Variable: ${{ needs.set-data.outputs.output_variable }}"
          echo "Environment Variable: ${{ env.env_variable }}"
          echo "Environment Variable Step: ${{ env.env_variable_step }}"
          echo "Output Step Variable: ${{ needs.set-data.outputs.output_step_variable }}"

      - name: Use environment variables in subsequent steps
        run: |
          echo "Environment Variable in step: ${{ env.env_variable_step }}"
