name: Build Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      volumes:
        - ubuntu_dockercache:/opt/dockercache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v5
        with:
          node-version: 20.16.x

      - name: Install yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install dependencies
        run: yarn install
        working-directory: ./password-xl-web

      - name: Get Meta
        id: meta
        run: |
          echo REPO_VERSION=$(node -p "require('./password-xl-web/package.json').version") >> $GITHUB_ENV

      - name: Set up Jdk21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x ./password-xl-service/gradlew

      - name: Build vue
        run: yarn run build
        working-directory: ./password-xl-web

      - name: Build jar
        working-directory: ./password-xl-service
        run: ./gradlew bootJar

      - name: Build exe
        working-directory: ./password-xl-web
        run: |
          yarn run dist-to-windows

      - name: zip package
        run: |
          && zip -r password-xl-web/dist.zip password-xl-web/dist
          && tar -zcvf password-xl-web/dist.tar.gz password-xl-web/dist

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{REPO_VERSION}}
            release_name: Release ${{REPO_VERSION}}
            draft: false
            prerelease: false

      - name: Upload Release Asset 1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: password-xl-web/dist.zip
          asset_name: password-xl-web-dist-${{REPO_VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset 2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: password-xl-web/dist.tar.gz
          asset_name: password-xl-web-dist-${{REPO_VERSION}}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset 3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: password-xl-web/build/password-XL-Windows-${{REPO_VERSION}}-Setup.exe
          asset_name: password-xl-win-${{REPO_VERSION}}.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset 4
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: password-xl-service/build/password-xl-service-${{REPO_VERSION}}-plain.jar
          asset_name: password-xl-service-${{REPO_VERSION}}.jar
          asset_content_type: application/octet-stream

          
