name: build service to Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: password-xl-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.4'

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: password-xl-service

      - name: Get version from build.gradle
        id: get_version
        run: echo "VERSION=$(./password-xl-service/gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{env.REPO_NAME}}:${{ env.VERSION }} -t ${{ secrets.DOCKERHUB_USERNAME }}/${{env.REPO_NAME}}:latest .
        working-directory: password-xl-service

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{env.REPO_NAME}}:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{env.REPO_NAME}}:latest