name: build service to Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Extract version from build.gradle
        id: get_version
        run: |
          VERSION=$(grep '^version =' password-xl-service/build.gradle | awk '{ print $3 }' | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd password-xl-service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:latest