name: build service to Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM with Java 21
        run: |
          GRAALVM_VERSION="21.3.0"
          JAVA_VERSION="21"
          curl -L -o graalvm.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java$JAVA_VERSION-linux-amd64-$GRAALVM_VERSION.tar.gz
          tar -xzf graalvm.tar.gz
          sudo mv graalvm-ce-java$JAVA_VERSION-$GRAALVM_VERSION /opt/
          sudo ln -s /opt/graalvm-ce-java$JAVA_VERSION-$GRAALVM_VERSION/bin/java /usr/bin/java
          sudo ln -s /opt/graalvm-ce-java$JAVA_VERSION-$GRAALVM_VERSION/bin/gu /usr/bin/gu
          java -version
          gu --version

      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Install Native Image
        run: gu install native-image

      - name: Build with Gradle
        working-directory: password-xl-service
        run: ./gradlew build

      - name: Build Native Image
        working-directory: password-xl-service
        run: ./gradlew bootBuildImage

      - name: Get version from build.gradle
        id: get_version
        working-directory: password-xl-service
        run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: password-xl-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:${{ env.VERSION }} -t ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/password-xl-service:latest
